### PR TITLE
feat: allow config generation without user prompt

### PR DESCRIPTION
**Pull request by fishgrimsby**
This PR will allow a config file to be generated without prompting the user for answers if they provide `--start-url` or `--region` as command options to `config generate`. If either one or both of these are omitted the user is prompted for an answer in the usual way.

It is an attempted implementation for #104

### CODE REVIEW

**Review by theurichde — CHANGES_REQUESTED** [review]
The change is quite easy, cool! Thanks for your effort 🚀 

I don't like to have all flags, especially the force, role-name and account-id, passed to the config command. 

You could try to extract the two flags needed for the config to a separate configFlag slice, pass those flags to the ConfigAction and append it later to the initFlags.

**Comment by fishgrimsby** [comment]
@theurichde Thanks for looking so promptly. You're absolutely right, it makes no sense to pass them all! I'll have a play and push some changes

**Comment by fishgrimsby** [comment]
@theurichde I've made a change as requested. It's perhaps not quite as you suggested as I didn't understand about appending it later. If it does need doing a different way then let me know and I'll give it a go!

**Comment by theurichde** [comment]
Hi @fishgrimsby! 

What I meant by appending the flags, is, that you could have added those both flags into a separate configFlags slice, pass those to the GenerateConfigAction and append them directly to initialFlags like below:
 
```
configFlags := []cli.Flag{ [startURL and region here] }
initialFlags := []cli.Flag{ [all other needed flags go here] }
initialFlags = append(initialFlags, configFlags...)
```

This would be less errorprone as your current implementation depends on the order of the flags added, which could break when a new flag gets inserted before the e.g. start-url flag

**Comment by fishgrimsby** [comment]
@theurichde That makes sense, I think i was taking the word extract too literally 😄 
I've made the change as you suggested, I've reversed the order of the append to maintain the order of the initflags.
Thanks for the help! 👍

**Comment by theurichde** [comment]
Thank you! Merge incoming 🎈

**Review by theurichde — APPROVED** [review]

**Pull request merged**
